### ISSUE TITLE
Is there a way to make it work for the Microsoft Store/Xbox Game version?

### ISSUE THREAD

**Issue by VB2095** [Lyall/Overcooked2Fix#4]
As the title says. I have the game with game pass and a ultrawide screen, would love to play it full resolution. @Lyall Your work is awesome but it would be even more awesome if we can use it with xbox game pc version :) 

thanks

**Comment by Taimoor-Tariq** [comment]
Did you figure out how?

**Comment by VB2095** [comment]
Sadly not. I bought the All you can eat version on steam hoping this fix would work but nope, stuck at 2560 x 1440 not ultrawide. It would be better if it worked, sure, but for now it's bearable

**Comment by Taimoor-Tariq** [comment]
I just unzipped the "epic" version in the Xbox game directory and I was able to play it at 5120 x 1440
